name: Build

on:
  push:
    branches:
    - master

jobs:
build:
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v2
  - name: Install dependencies
    run: |
      sudo apt-get install -y libsdl2-dev
  - name: Run make
    run: |
      make
